### ISSUE TITLE
change xwalk-webview without restarting the app

### ISSUE THREAD

**Issue by BarTsouri** [crosswalk-project/crosswalk-web-driver#15]
Hello,

My team and I would like to thank you for your latest contribution in field of automation, the crosswalk-webdriver.

I am very interested to know if there is a way to change the webdriver's context to another webview without restarting the whole app. Each webview is hosted in a different activity.

You see, we have implemented a double webview mechanism in our app, and need a way to make automate testing on the second webview when coming from the initial one.

If you have any clue, I would love to know.

Thanks in advance,

**Comment by wuyuehang** [comment]
There's an inner mechanism which records window handles with webview id.
For example, if the webview id appears to be "abcdef...", then the related window handle will be "CDwindow-abcdef...".
As our automation scripts reuse selenium remote webdriver class referring to https://selenium-python.readthedocs.org/api.html#module-selenium.webdriver.remote.webdriver.
So I guess the api "driver.switch_to_window" and "driver.switch_to" will do your help.

**Comment by BarTsouri** [comment]
I just tried your suggestion, and I can't make any progress with that.
As soon as the application completely loads up, I execute the following command:

```
driver.getWindowHandle().then(function(){console.log(arguments)});
```

and the output is:
{ '0': 'CDwindow-EC71C3E0-5996-BF03-A586-81B9CDC77F95' }

When the new activity with the new xwalk window loads up, I execute the same command but get only the window id above.

In this case I can't call driver.switchTo.window, because it doesn't exist for the webdriver.
Will be happy to know if you have more suggestions

**Comment by BarTsouri** [comment]
Just found a chromedriver capability that can help us solve the problem. Chromedriver can get the following capability: `androidUseRunningApp: true`.

You can look it up in https://sites.google.com/a/chromium.org/chromedriver/getting-started/getting-started---android and look for androidUseRunningApp.
Unfortunately when passing this capability to I get an error that it's not recognized.

The code

```
var webdriver = require('selenium-webdriver');

 var caps = {
 'browserName': 'xwalk',
 'xwalkOptions': {
 'androidPackage': 'org.capriza.store',
 'androidActivity': '.LaunchActivity',
 androidUseRunningApp: true
 }
 };

 var driver = new webdriver.Builder().
 usingServer('http://localhost:9515').
 withCapabilities(caps).
 build();
```

The error

```
/data/dev/automation/node_modules/selenium-webdriver/lib/webdriver/promise.js:1761
      throw error;
            ^
UnknownError: unknown error: cannot parse capability: xwalkOptions
from unknown error: unrecognized xwalk option: androidUseRunningApp
  (Driver info: xwalkdriver=2.5.ede663c5c5362a073e538cdabacf85612bc9e16a,platform=Linux 3.11.0-12-generic x86_64)
    at new bot.Error (/data/dev/automation/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)
    at Object.bot.response.checkResponse (/data/dev/automation/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /data/dev/automation/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:152:24
    at /data/dev/automation/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (/data/dev/automation/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at notify (/data/dev/automation/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
    at notifyAll (/data/dev/automation/node_modules/selenium-webdriver/lib/webdriver/promise.js:442:7)
    at resolve (/data/dev/automation/node_modules/selenium-webdriver/lib/webdriver/promise.js:420:7)
    at fulfill (/data/dev/automation/node_modules/selenium-webdriver/lib/webdriver/promise.js:535:5)
    at /data/dev/automation/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
==== async task ====
WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/data/dev/automation/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:149:22)
    at Function.webdriver.WebDriver.createSession (/data/dev/automation/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:123:30)
    at Builder.build (/data/dev/automation/node_modules/selenium-webdriver/builder.js:294:22)
    at repl:4:1
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
```

**Comment by wuyuehang** [comment]
So please try xwalkdriver64_20140919/xwalkdriver32_20140919, the feature using running apps is removed in xwalkdriver release.

**Comment by BarTsouri** [comment]
Thank you, it works.
Will you be able to insert this flag back again in the future?
It will help me a lot!

**Comment by wuyuehang** [comment]
@BarTsouri 
Removing this feature is intended to adjust both set up interfaces for Tizen and Android after refactoring device-related classes. They differ a lot inside.

Could you describe how you test your multi-webviews? 
For example, driver0 relates with activity0 and your 1st webview while driver1 relates with activity1 and 2nd webview. And then switch between the two driver handlers?

For the update commits (branch from xwalkdriver_for_crosswalk_9) is aimed at fixing Tizen issues. The main parts of functions almost stay the same on Android side.

**Comment by BarTsouri** [comment]
Dear @wuyuehang ,

First of all, thank you.

We take the concept of mobile-web-application very seriously. The app consists of two activities, .LaunchActivity and .LogicActivity, where both of them instantiate instance of xwalk. The LaunchActivity serves as a portal for the application, and the LogicActivity shows additional information. We think that the app is awesome in the way that It uses real Android design pattern of Activities.

With your suggestion to use xwalkdriver64_20140919, I instantiate webdriver#1 on LaunchActivity, and when transitioning to LogicActivity I do instantiate webdriver#2 with androidUseRunningApp flag. Hope that it makes it clear.

I am only asking that if you make extensive changes in the xwalk-webdriver, please do not forget to add the androidUseRunningApp flag, so we'll be able to make e2e tests on our system.

Thanks again.

**Comment by wuyuehang** [comment]
> I instantiate webdriver#1 on LaunchActivity, and when transitioning to LogicActivity I do instantiate webdriver#2 with androidUseRunningApp flag. Hope that it makes it clear.

@BarTsouri  All right, it's clear to my question. 
Thanks for your detailed report and I'll try restore this feature the next update :D

**Comment by CalebRouleau** [comment]
Any update on this? Was this feature restored in the next update? I'm trying to access whether this feature still works or not.
