### ISSUE TITLE
Build for Linux problems

### ISSUE THREAD

**Issue by BarTsouri** [crosswalk-project/crosswalk-web-driver#16]
I want to modify the existing xwalkdriver and need to build it. Here are the actions I took so far:
1. Cloned crosswalk-web-driver repo
2. cloned crosswalk-project from https://github.com/crosswalk-project/crosswalk.git
3. patched crosswalk-web-driver/xwalk_tests.gypi to crosswalk/xwalk_tests.gypi
4. copied crosswalk-web-driver/xwalkdriver to crosswalk/test/
5. export GYP_GENERATORS='ninja'
6. went to crosswalk parent directory
7. GYP_DEFINES="target_arch=x64 clang=1" crosswalk/gyp_xwalk
8. Got an Error: 

```
Traceback (most recent call last):
  File "crosswalk/gyp_xwalk", line 22, in <module>
    import gyp
ImportError: No module named gyp
```

9installed gyp `sudo apt-get install gyp`

10Got an Error:

```
Traceback (most recent call last):
  File "crosswalk/gyp_xwalk", line 26, in <module>
    import gyp_environment
ImportError: No module named gyp_environment
```

I am not sure how to proceed from here

**Comment by wuyuehang** [comment]
xwalkdriver build depends on xwalk project which is based on chromium project.
1. Please follow the instructions at https://crosswalk-project.org/contribute/building_crosswalk.html to sync the whole src not only the chromium-crosswalk.git/crosswalk.git
2. Then follow the guild on "README.md" in xwalkdriver source code.

**Comment by mishra-bhokali** [comment]
Hi wuyuehang,
I am also facing same issue. I have followed all steps properly but not sure why it is happening.
Please help to resolve.
Can you please explain your step 1 ?
