### ISSUE TITLE
Updating crosswalk driver to recent chromedriver releases

### ISSUE THREAD

**Issue by eduramiba** [crosswalk-project/crosswalk-web-driver#21]
Hi,
Are there plans to update this webdriver to fix old issues such as 

https://bugs.chromium.org/p/chromedriver/issues/detail?id=1225

 (fixed in chromedriver 2.20) ?

Thank you

**Comment by rkavalap** [comment]
@eduramiba 
https://github.com/rkavalap/crosswalk-web-driver/releases
